feat: use install script in cloned repo

diff --git a/tools/bin/install b/tools/bin/install
--- a/tools/bin/install
+++ b/tools/bin/install
@@ -5,7 +5,7 @@
 # ARG_OPTIONAL_BOOLEAN([development],[d],[Install development requirements])
 # ARG_POSITIONAL_SINGLE([destination],[Project path, '~/.config/workstation' by default or './workstation' for --development option],[""])
 # ARG_HELP([Get the workstation Ansible configuration, install the configuration dependencies and configuration setup])
-# ARG_VERSION([_ARGBASH_VERSION])
+# DEFINE_SCRIPT_DIR_GNU()
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
@@ -24,7 +24,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='dhv'
+	local first_option all_short_options='dh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -39,11 +39,10 @@ _arg_development="off"
 print_help()
 {
 	printf '%s\n' "Get the workstation Ansible configuration, install the configuration dependencies and configuration setup"
-	printf 'Usage: %s [-d|--(no-)development] [-h|--help] [-v|--version] [<destination>]\n' "$0"
+	printf 'Usage: %s [-d|--(no-)development] [-h|--help] [<destination>]\n' "$0"
 	printf '\t%s\n' "<destination>: Project path, '~/.config/workstation' by default or './workstation' for --development option (default: '""')"
 	printf '\t%s\n' "-d, --development, --no-development: Install development requirements (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
-	printf '\t%s\n' "-v, --version: Prints version"
 }
 
 
@@ -72,14 +71,6 @@ parse_commandline()
 				;;
 			-h*)
 				print_help
-				exit 0
-				;;
-			-v|--version)
-				_ARGBASH_VERSION
-				exit 0
-				;;
-			-v*)
-				_ARGBASH_VERSION
 				exit 0
 				;;
 			*)
@@ -118,10 +109,15 @@ handle_passed_args_count
 assign_positional_args 1 "${_positionals[@]}"
 
 # OTHER STUFF GENERATED BY Argbash
+script_dir="$(cd "$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
+
+SCRIPT_DIR_NAME="${script_dir%"${script_dir##*[!/]}"}" # extglob-free multi-trailing-/ trim
+SCRIPT_DIR_NAME="${SCRIPT_DIR_NAME##*/}"               # remove everything before the last /
+SCRIPT_DIR_NAME=${SCRIPT_DIR_NAME:-/}                  # correct for dirname=/ case
 
 if [ -z "$_arg_destination" ]
 then
@@ -133,6 +129,11 @@ then
   fi
 else
   TARGET_PATH="$_arg_destination"
+fi
+
+if [ "$SCRIPT_DIR_NAME" = bin ]
+then
+  TARGET_PATH=$(readlink -f "$script_dir/../../")
 fi
 
 TARGET_DIR=$(dirname "$TARGET_PATH")
@@ -190,8 +191,13 @@ then
 fi
 
 export_path
-ensure_target_dir
-clone_configuration
+
+if [ "$SCRIPT_DIR_NAME" != bin ]
+then
+  ensure_target_dir
+  clone_configuration
+fi
+
 install_ansible_galaxy_roles
 setup_ansible_vars
 
